tasks:
  - name: cleanup
    taskRef:
      name: cleanup-task
    runAfter:
      - test-task
    params:
      - name: path
        value: /workspace/source

- name: nose-test
    taskRef:
      name: nose-test-task
    params:
      - name: test-path
        value: /workspace/source/tests